name: install-and-test-workflow

on: [push]

env:
  UV_INDEX: https://gitlab.mpcdf.mpg.de/api/v4/projects/2187/packages/pypi/simple

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Test with pytest
        run: |
          uv run pytest -sv

  ruff-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run Ruff
        run: uv run ruff check .

  # ruff-formatting:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install uv
  #       uses: astral-sh/setup-uv@v5
  #     - name: Check Format
  #       run: uv run ruff format . --check